export default {
  title: "Better Friend",
  header: "Better Friend",
  addFriendHeader: "Add Friend",
  addFriendBtn: "Add Friend",
  friendDetailHeader: "Friend Details",
  settingsHeader: "Settings",
  createProfile: "Create Profile",
  changeLayout: "Change Layout",
  changeLanguage: "Change Language",
  changeOrder: "Change Order",
  exportImportFriends: "Export/Import Friends",
  importContacts: "Import Contacts",
  changeDescription: "Change Default Description",
  reportBug: "Report a Bug",
  resetApp: "Reset App",
  redeemCode: "Redeem Code",
  searchInput: "Search friends...",
  friendNameInput: "Enter friend name",
  friendNickInput: "Enter friend nickname",
  friendTimezoneInput: "Enter friend Timezone",
  friendBirthdayInput: "Enter friend birthday",
  friendTagsInput: "e.g., work, gym",
  friendNameLabel: "Name:",
  friendNickLabel: "Nickname:",
  friendTimezoneLabel: "Timezone:",
  friendNumberLabel: "Number:",
  friendBirthdayLabel: "Birthday:",
  friendMeetdayLabel: "Meet day:",
  friendImageLabel: "Upload Image:",
  nowBtn: "Now",
  friendTagsLabel: "Tags (comma-separated):",
  totalContacts: "Total Contacts:",
  permissionDenied: "Permission Denied",
  unknown: "Unknown",
  noTags: "No Tags",
  noNotifications: "No Notifications yet.",
  friendNotFound: "Friend ${FRIEND} not found, lets add them!",
  friendNotFoundParams:
    "Friend not found, try adjusting your search parameters",
  birthday: "Birthday",
  meetday: "Meetday",
  totalContactsSelected: "Total Contacts Selected:",
  alertErrorReset: "There was an error resetting the app. Please try again.",
  errorLoadNotifications: "Failed to load notifications.",
  modal: {
    deleteNotification: "Delete this notification?",
    friendNameRequired: "Please enter a friend's name.",
    default: {
      title: "Confirm Action",
      message: "Are you sure?",
      confirmText: "Confirm",
      cancelText: "Cancel",
    },
    revert: {
      title: "Are you sure? Your settings will be reverted to the default",
    },
    delete: {
      title: "Settings deleted. Delete all information?",
    },
    tags: {
      title: "Edit Tags",
      description: "Select tags to attach to this friend.",
      message: "Are you sure?",
      confirmText: "Save",
      cancelText: "Cancel",
    },
    importContacts: {
      title: "Add Friends",
      message:
        "Would you like to import contacts? You can always access contact importing later in the settings.",
      confirmText: "Import",
      cancelText: "Add Manually",
    },
    deleteFriend: {
      title: "Are you sure? All information will be deleted!",
    },
    list: {
      title: "Please select an item:",
      message: "Select Item",
      confirmText: "Select",
      cancelText: "Cancel",
    },
    langs: {
      title: "Select Language",
      message: "Choose your preferred language:",
      confirmText: "Apply",
      cancelText: "Cancel",
    },
    order: {
      title: "Change Order",
      message: "Sort friends by:",
      confirmText: "Confirm",
      cancelText: "Cancel",
      options: [
        "Alphabetically Ascending",
        "Alphabetically Descending",
        "Ascending Creation Date",
        "Descending Creation Date",
        "Most Interacted",
        "Least Interacted",
        "Last Edited",
        // "Upcoming Birthday",
      ],
    },
    orderConfirm: {
      title: "Order Changed",
      message: "Order successfully changed to",
      confirmText: "OK",
    },
    langConfirm: {
      title: "Language Changed",
      message: "Language successfully changed to English.",
      confirmText: "OK",
    },
    defaultDesc: {
      title: "Update Description",
      message: "Enter your default friend description:",
      confirmText: "Save",
      cancelText: "Cancel",
    },
    fileUpload: {
      title: "Update Description",
      message: "Change your friend's profile picture:",
      confirmText: "Upload",
      cancelText: "Cancel",
    },
    prompt: {
      title: "Input Required",
      message: "Please enter a code:",
      confirmText: "OK",
      cancelText: "Cancel",
    },
    addNotification: {
      title: "Add Notification",
      message: "Set a new notification for this friend",
      confirmText: "Schedule",
      labels: {
        title: "Title",
        titlePlaceholder: "e.g. Call for birthday",
        body: "Message",
        bodyPlaceholder: "Details...",
        date: "Date & Time",
        repeats: "Repeats?",
      },
      priorities: {
        low: "Low",
        medium: "Medium",
        high: "High",
      },
      repeats: {
        no: "No",
        year: "Yearly",
        month: "Monthly",
        week: "Weekly",
        day: "Daily",
      },
    },
    editFriend: {
      title: "Edit Friend",
      message: "Update the friend's information below:",
      labels: {
        name: "Name",
        nick: "Nickname",
        contact: "Contact",
        timezone: "Timezone",
        birthday: "Birthday",
        meetday: "Meet Day",
      },
      placeholders: {
        contact: "@instagram or +55 11 1234-12345",
      },
    },
  },
  "notification-btn": "Notification",
  defaultFriendDescription: `*"A good friend is like a four-leaf clover; hard to find and lucky to have."*\n\n# Click here to edit the notes!`,
  dateNotInformed: "Date not informed",
  noNewContactsFound: "No new contacts found",
  contactsError: "Error loading contacts",
  timezoneOptions: {
    "-12": "UTC-12: Baker Island, Howland Island",
    "-11": "UTC-11: American Samoa, Niue",
    "-10": "UTC-10: Hawaii, French Polynesia (most)",
    "-9": "UTC-9: Alaska, Gambier Islands (France)",
    "-8": "UTC-8: Pacific Time Baja California (Mexico)",
    "-7": "UTC-7: Mountain Time Sonora (Mexico)",
    "-6": "UTC-6: Central Time",
    "-5": "UTC-5: Eastern Time Cuba, Colombia, Ecuador (mainland)",
    "-4": "UTC-4: Atlantic Time (Canada), Venezuela, Bolivia, Chile (mainland)",
    "-3.5": "UTC-3:30: Newfoundland (Canada)",
    "-3": "UTC-3: Brasília Time, Argentina, Uruguay",
    "-2": "UTC-2: Fernando de Noronha (Brazil), South Georgia",
    "-1": "UTC-1: Azores (Portugal), Cape Verde",
    0: "UTC+0: United Kingdom, Ireland, Portugal, Iceland, West Africa",
    1: "UTC+1: Central Europe, West Africa Time",
    2: "UTC+2: Eastern Europe, Egypt, South Africa",
    3: "UTC+3: Russia, East Africa, Arabia",
    3.5: "UTC+3:30: Iran",
    4: "UTC+4: United Arab Emirates, Oman, Azerbaijan",
    4.5: "UTC+4:30: Afghanistan",
    5: "UTC+5: Pakistan, Uzbekistan",
    5.5: "UTC+5:30: India, Sri Lanka",
    5.75: "UTC+5:45: Nepal",
    6: "UTC+6: Bangladesh, Bhutan, Kazakhstan",
    6.5: "UTC+6:30: Myanmar, Cocos Islands",
    7: "UTC+7: Thailand, Vietnam, Indonesia",
    8: "UTC+8: China, Philippines, Malaysia, Singapore, Western Australia",
    9: "UTC+9: Japan, South Korea, Eastern Indonesia",
    9.5: "UTC+9:30: South Australia, Northern Territory (Australia)",
    10: "UTC+10: Queensland, Papua New Guinea",
    10.5: "UTC+10:30: Lord Howe Island",
    11: "UTC+11: New Caledonia, Solomon Islands",
    12: "UTC+12: New Zealand, Fiji, Marshall Islands",
    12.75: "UTC+12:45: Chatham Islands",
    13: "UTC+13: Tonga, Samoa, Tokelau",
    14: "UTC+14: Line Islands",
  },
  themeText: "",
  settings: {
    light: "Swap to Light Mode",
    dark: "Swap to Dark Mode",
  },
  notifications: {
    meetday: {
      title: "📅 Meet Day Anniversary",
      body: "You have been friends with ${nickName} since ${year}!",
    },
    birthday: {
      title: "🎉 ${name}'s Birthday!",
      body: "Wish ${nickName} a happy birthday!",
    },
    upcomingBirthday: {
      title: "🎉 ${name}'s Birthday is in a week!",
      body: "Be sure to get them a gift!",
    },
    interaction: {
      title: "💭 Reminder about ${displayName}",
      body: "Don't forget to reach out to ${displayName}!",
    },
  },
  sortHeader: "Sort Options",
  emptyMessage: "No friends added yet. Add some friends!",
  "interaction-btn-disabled": "Add Friend Contact",
};
