export default {
  title: "Better Friend",
  header: "Better Friend",
  addFriendHeader: "Agregar Amigo",
  addFriendBtn: "Agregar Amigo",
  friendDetailHeader: "Detalles del Amigo",
  settingsHeader: "Configuraciones",
  createProfile: "Crear Perfil",
  changeLayout: "Cambiar Diseño",
  changeLanguage: "Cambiar Idioma",
  changeOrder: "Cambiar Orden",
  exportImportFriends: "Exportar/Importar Amigos",
  importContacts: "Importar Contactos",
  changeDescription: "Cambiar Descripción Predeterminada",
  reportBug: "Informar Error",
  resetApp: "Restablecer App",
  redeemCode: "Canjear Código",
  searchInput: "Buscar amigos...",
  friendNameInput: "Ingresa el nombre",
  friendNickInput: "Ingresa el apodo",
  friendTimezoneInput: "Ingresa la zona horaria",
  friendBirthdayInput: "Ingresa el cumpleaños",
  friendMeetdayLabel: "Cuando conociste:",
  friendImageLabel: "Subir foto:",
  friendTagsInput: "ej.: trabajo, gimnasio",
  friendNameLabel: "Nombre:",
  friendNickLabel: "Apodo:",
  friendTimezoneLabel: "Zona horaria:",
  friendNumberLabel: "Número:",
  friendBirthdayLabel: "Cumpleaños:",
  nowBtn: "Hoy",
  friendTagsLabel: "Etiquetas (separadas por comas):",
  totalContacts: "Total de Contactos:",
  permissionDenied: "Permiso Denegado",
  unknown: "Desconocido",
  noTags: "Sin Etiquetas",
  noNotifications: "Sin notificaciones aún.",
  friendNotFound: "Amigo ${FRIEND} no encontrado, ¡vamos a agregarlo!",
  friendNotFoundParams:
    "Amigo no encontrado, intenta ajustar tus parámetros de búsqueda",
  birthday: "Cumpleaños",
  meetday: "Día en que conocieron",
  totalContactsSelected: "Total de Contactos Seleccionados:",
  alertErrorReset: "Hubo un error al restablecer la app. Inténtalo de nuevo.",
  modal: {
    default: {
      title: "Confirmar Acción",
      message: "¿Estás seguro?",
      confirmText: "Confirmar",
      cancelText: "Cancelar",
    },
    revert: {
      title:
        "¿Estás seguro? Tus configuraciones se revertirán al valor predeterminado",
    },
    delete: {
      title: "Configuraciones eliminadas. ¿Eliminar toda la información?",
    },
    tags: {
      title: "Editar Etiquetas",
      description: "Selecciona las etiquetas para adjuntar a este amigo.",
      message: "¿Estás seguro?",
      confirmText: "Guardar",
      cancelText: "Cancelar",
    },
    importContacts: {
      title: "Agregar Amigos",
      message:
        "¿Te gustaría importar contactos? Siempre puedes importar más tarde desde Configuraciones.",
      confirmText: "Importar",
      cancelText: "Agregar manualmente",
    },
    deleteFriend: {
      title: "¿Estás seguro? ¡Toda la información será eliminada!",
    },
    list: {
      title: "Por favor selecciona un elemento:",
      message: "Seleccionar elemento",
      confirmText: "Seleccionar",
      cancelText: "Cancelar",
    },
    langs: {
      title: "Seleccionar Idioma",
      message: "Elige tu idioma preferido:",
      confirmText: "Aplicar",
      cancelText: "Cancelar",
    },
    langConfirm: {
      title: "Idioma Cambiado",
      message: "El idioma se cambió correctamente a Español.",
      confirmText: "OK",
    },
    order: {
      title: "Cambiar Orden",
      message: "Cambia el orden de visualización de tus amigos",
      confirmText: "Confirmar",
      cancelText: "Cancelar",
      options: [
        "Alfabéticamente Ascendente",
        "Alfabéticamente Descendente",
        "Fecha de Creación Ascendente",
        "Fecha de Creación Descendente",
        "Más Interactuado",
        "Menos Interactuado",
        "Última Edición",
        // "Cumpleaños más cercano",
      ],
    },
    orderConfirm: {
      title: "Orden Cambiado",
      message: "Orden cambiado exitosamente a",
      confirmText: "OK",
    },
    defaultDesc: {
      title: "Actualizar Descripción",
      message: "Ingresa tu descripción predeterminada del amigo:",
      confirmText: "Guardar",
      cancelText: "Cancelar",
    },
    fileUpload: {
      title: "Actualizar Foto",
      message: "Cambia la foto de perfil de tu amigo:",
      confirmText: "Subir",
      cancelText: "Cancelar",
    },
    prompt: {
      title: "Entrada Requerida",
      message: "Por favor ingresa un código:",
      confirmText: "OK",
      cancelText: "Cancelar",
    },
    addNotification: {
      title: "Agregar Notificación",
      message: "Configurar una nueva notificación para este amigo",
      confirmText: "Programar",
      labels: {
        title: "Título",
        titlePlaceholder: "ej. Llamar por cumpleaños",
        body: "Mensaje",
        bodyPlaceholder: "Detalles...",
        date: "Fecha y Hora",
        repeats: "Repetir?",
      },
      priorities: {
        low: "Baja",
        medium: "Media",
        high: "Alta",
      },
      repeats: {
        no: "No",
        year: "Anualmente",
        month: "Mensualmente",
        week: "Semanalmente",
        day: "Diariamente",
      },
    },
    editFriend: {
      title: "Editar Amigo",
      message: "Actualice la información del amigo a continuación:",
      labels: {
        name: "Nombre",
        nick: "Apodo",
        contact: "Contacto",
        timezone: "Zona Horaria",
        birthday: "Cumpleaños",
        meetday: "Día que se conocieron",
      },
      placeholders: {
        contact: "@instagram o +55 11 1234-12345",
      },
    },
  },
  "notification-btn": "Notificación",
  defaultFriendDescription: `*"Un buen amigo es como un trébol de cuatro hojas; difícil de encontrar y afortunado de tener."*\n\n# ¡Haz clic aquí para editar las notas!`,
  dateNotInformed: "Fecha no informada",
  noNewContactsFound: "No se encontraron nuevos contactos",
  contactsError: "Error al cargar contactos",
  timezoneOptions: {
    "-12": "UTC-12: Isla Baker, Isla Howland",
    "-11": "UTC-11: Samoa Americana, Niue",
    "-10": "UTC-10: Hawái, Polinesia Francesa (mayoría)",
    "-9": "UTC-9: Alaska, Islas Gambier (Francia)",
    "-8": "UTC-8: Hora del Pacífico, Baja California (México)",
    "-7": "UTC-7: Hora de la Montaña, Sonora (México)",
    "-6": "UTC-6: Hora Central",
    "-5": "UTC-5: Hora del Este, Cuba, Colombia, Ecuador (continental)",
    "-4": "UTC-4: Hora del Atlántico (Canadá), Venezuela, Bolivia, Chile (continental)",
    "-3.5": "UTC-3:30: Terranova (Canadá)",
    "-3": "UTC-3: Hora de Brasilia, Argentina, Uruguay",
    "-2": "UTC-2: Fernando de Noronha (Brasil), Georgia del Sur",
    "-1": "UTC-1: Azores (Portugal), Cabo Verde",
    0: "UTC+0: Reino Unido, Irlanda, Portugal, Islandia, África Occidental",
    1: "UTC+1: Europa Central, Hora de África Occidental",
    2: "UTC+2: Europa Oriental, Egipto, Sudáfrica",
    3: "UTC+3: Rusia, África Oriental, Arabia",
    3.5: "UTC+3:30: Irán",
    4: "UTC+4: Emiratos Árabes Unidos, Omán, Azerbaiyán",
    4.5: "UTC+4:30: Afganistán",
    5: "UTC+5: Pakistán, Uzbekistán",
    5.5: "UTC+5:30: India, Sri Lanka",
    5.75: "UTC+5:45: Nepal",
    6: "UTC+6: Bangladesh, Bután, Kazajistán",
    6.5: "UTC+6:30: Myanmar, Islas Cocos",
    7: "UTC+7: Tailandia, Vietnam, Indonesia",
    8: "UTC+8: China, Filipinas, Malasia, Singapur, Australia Occidental",
    9: "UTC+9: Japón, Corea del Sur, Indonesia Oriental",
    9.5: "UTC+9:30: Australia Meridional, Territorio del Norte (Australia)",
    10: "UTC+10: Queensland, Papúa Nueva Guinea",
    10.5: "UTC+10:30: Isla Lord Howe",
    11: "UTC+11: Nueva Caledonia, Islas Salomón",
    12: "UTC+12: Nueva Zelanda, Fiyi, Islas Marshall",
    12.75: "UTC+12:45: Islas Chatham",
    13: "UTC+13: Tonga, Samoa, Tokelau",
    14: "UTC+14: Islas Line",
  },
  themeText: "",
  settings: {
    light: "Cambiar a Modo Claro",
    dark: "Cambiar a Modo Oscuro",
  },
  notifications: {
    meetday: {
      title: "📅 Aniversario del Día en que se conocieron",
      body: "¡Eres amigo de ${nickName} desde ${year}!",
    },
    birthday: {
      title: "🎉 ¡Cumpleaños de ${name}!",
      body: "¡Desea a ${nickName} un feliz cumpleaños!",
    },
    upcomingBirthday: {
      title: "🎉 ¡${name} tiene un cumpleaños en una semana!",
      body: "¡Asegúrate de regalarles un regalo!",
    },
    interaction: {
      title: "💭 Recordatorio sobre ${displayName}",
      body: "¡No olvides ponerte en contacto con ${displayName}!",
    },
  },
  sortHeader: "Opciones de Ordenamiento",
  emptyMessage: "No hay amigos agregados aún. ¡Agrega algunos amigos!",
  "interaction-btn-disabled": "Adiciona amigo",
};
