export default {
  title: "Better Friend",
  header: "Better Friend",
  addFriendHeader: "Adicionar Amigo",
  addFriendBtn: "Adicionar Amigo",
  friendDetailHeader: "Detalhes do Amigo",
  settingsHeader: "Configurações",
  createProfile: "Criar Perfil",
  changeLayout: "Trocar Layout",
  changeLanguage: "Trocar Língua",
  changeOrder: "Cambiar Orden",
  exportImportFriends: "Exportar/Importar Amigos",
  importContacts: "Importar Contatos",
  changeDescription: "Trocar Descrição Padrão",
  reportBug: "Relatar Problema",
  resetApp: "Resetar App",
  redeemCode: "Resgatar Código",
  searchInput: "Procurar amigos...",
  friendNameInput: "Digite o nome do amigo",
  friendNickInput: "Digite o apelido do amigo",
  friendTimezoneInput: "Digite a zona horária",
  friendBirthdayInput: "Digite a data de nascimento",
  friendTagsInput: "ex.: trabalho, academia",
  friendNameLabel: "Nome:",
  friendImageLabel: "Subir foto:",
  nowBtn: "Hoje",
  friendMeetdayLabel: "Quando conheceu:",
  friendNickLabel: "Apelido:",
  friendTimezoneLabel: "Zona horária:",
  friendNumberLabel: "Número:",
  friendBirthdayLabel: "Aniversário:",
  friendTagsLabel: "Tags (separadas por vírgula)",

  totalContacts: "Total de Contatos:",
  permissionDenied: "Permissão negada",
  unknown: "Desconhecido",
  noTags: "Sem tags",
  noNotifications: "Sem notificações ainda.",
  friendNotFound: "Amigo ${FRIEND} não encontrado, vamos adicioná-lo!",
  friendNotFoundParams:
    "Amigo não encontrado, tente ajustar seus parâmetros de busca",
  birthday: "Aniversário",
  meetday: "Dia que conheceu",
  totalContactsSelected: "Total de Contatos Selecionados:",
  alertErrorReset: "Houve um erro ao resetar o app. Tente novamente.",
  modal: {
    default: {
      title: "Confirmar Ação",
      message: "Tem certeza?",
      confirmText: "Confirmar",
      cancelText: "Cancelar",
    },
    revert: {
      title: "Tem certeza? Suas configurações serão revertidas para o padrão",
    },
    delete: {
      title: "Configurações excluídas. Excluir todas as informações?",
    },
    tags: {
      title: "Editar Tags",
      description: "Selecione as tags para anexar a este amigo.",
      message: "Tem certeza?",
      confirmText: "Salvar",
      cancelText: "Cancelar",
    },
    importContacts: {
      title: "Adicionar Amigos",
      message:
        "Gostaria de importar contatos? Você sempre pode importar depois nas configurações.",
      confirmText: "Importar",
      cancelText: "Adicionar manualmente",
    },
    deleteFriend: {
      title: "Tem certeza? Todas as informações serão excluídas!",
    },
    list: {
      title: "Selecione um item:",
      message: "Selecionar Item",
      confirmText: "Selecionar",
      cancelText: "Cancelar",
    },
    langs: {
      title: "Selecionar Idioma",
      message: "Escolha seu idioma preferido:",
      confirmText: "Aplicar",
      cancelText: "Cancelar",
    },
    langConfirm: {
      title: "Idioma Alterado",
      message: "Idioma alterado com sucesso para Portuguese.",
      confirmText: "OK",
    },
    order: {
      title: "Alterar Ordem",
      message: "Alterar a ordem de exibição dos seus amigos",
      confirmText: "Confirmar",
      cancelText: "Cancelar",
      options: [
        "Alfabeticamente Crescente",
        "Alfabeticamente Decrescente",
        "Data de Criação Crescente",
        "Data de Criação Decrescente",
        "Mais Interagido",
        "Menos Interagido",
        "Última Edição",
        // "Aniversário mais próximo",
      ],
    },
    orderConfirm: {
      title: "Ordem Alterada",
      message: "Ordem alterada com sucesso para",
      confirmText: "OK",
    },
    defaultDesc: {
      title: "Atualizar Descrição",
      message: "Digite a descrição padrão do amigo:",
      confirmText: "Salvar",
      cancelText: "Cancelar",
    },
    fileUpload: {
      title: "Atualizar Foto",
      message: "Troque a foto de perfil do seu amigo:",
      confirmText: "Enviar",
      cancelText: "Cancelar",
    },
    prompt: {
      title: "Entrada Necessária",
      message: "Por favor insira um código:",
      confirmText: "OK",
      cancelText: "Cancelar",
    },
    addNotification: {
      title: "Adicionar Notificação",
      message: "Definir uma nova notificação para este amigo",
      confirmText: "Agendar",
      labels: {
        title: "Título",
        titlePlaceholder: "ex. Ligar para aniversário",
        body: "Mensagem",
        bodyPlaceholder: "Detalhes...",
        date: "Data e Hora",
        repeats: "Repete?",
      },
      priorities: {
        low: "Baixa",
        medium: "Média",
        high: "Alta",
      },
      repeats: {
        no: "Não",
        year: "Anualmente",
        month: "Mensalmente",
        week: "Semanalmente",
        day: "Diariamente",
      },
    },
    editFriend: {
      title: "Editar Amigo",
      message: "Atualize as informações do amigo abaixo:",
      labels: {
        name: "Nome",
        nick: "Apelido",
        contact: "Contato",
        timezone: "Fuso Horário",
        birthday: "Aniversário",
        meetday: "Dia que conheceu",
      },
      placeholders: {
        contact: "@instagram ou +55 11 1234-12345",
      },
    },
  },
  "notification-btn": "Notificação",
  dateNotInformed: "Data não informada",
  defaultFriendDescription:
    '*"Um bom amigo é como um trevo de quatro folhas; difícil de encontrar e uma sorte ter."*\n\n# Clique aqui para editar as notas!',
  noNewContactsFound: "Nenhum novo contato encontrado",
  contactsError: "Erro ao carregar contatos",
  timezoneOptions: {
    "-12": "UTC-12: Ilha Baker, Ilha Howland (EUA)",
    "-11": "UTC-11: Samoa Americana, Niue",
    "-10": "UTC-10: Havaí (EUA), Polinésia Francesa (maior parte)",
    "-9": "UTC-9: Alasca (EUA), Ilhas Gambier (França)",
    "-8": "UTC-8: Hora do Pacífico (EUA/Canadá), Baja California (México)",
    "-7": "UTC-7: Hora das Montanhas (EUA/Canadá), Sonora (México)",
    "-6": "UTC-6: Hora Central (EUA/Canadá), América Central (maior parte)",
    "-5": "UTC-5: Hora do Leste (EUA/Canadá), Cuba, Colômbia, Equador (continental)",
    "-4": "UTC-4: Hora do Atlântico (Canadá), Venezuela, Bolívia, Chile (continental)",
    "-3.5": "UTC-3:30: Terra Nova (Canadá)",
    "-3": "UTC-3: Horário de Brasília (Brasil - DF, GO, MG, ES, RJ, SP, PR, SC, RS), Argentina, Uruguai",
    "-2": "UTC-2: Fernando de Noronha (Brasil), Geórgia do Sul",
    "-1": "UTC-1: Açores (Portugal), Cabo Verde",
    0: "UTC+0: Reino Unido, Irlanda, Portugal, Islândia, África Ocidental",
    1: "UTC+1: Europa Central, África Ocidental (verão)",
    2: "UTC+2: Europa Oriental, Egito, África do Sul",
    3: "UTC+3: Horário de Moscou (Rússia), África Oriental, Arábia",
    3.5: "UTC+3:30: Irã",
    4: "UTC+4: Emirados Árabes, Omã, Azerbaidjão",
    4.5: "UTC+4:30: Afeganistão",
    5: "UTC+5: Paquistão, Uzbequistão",
    5.5: "UTC+5:30: Índia, Sri Lanka",
    5.75: "UTC+5:45: Nepal",
    6: "UTC+6: Bangladesh, Butão, Cazaquistão (Almaty)",
    6.5: "UTC+6:30: Myanmar, Ilhas Cocos",
    7: "UTC+7: Tailândia, Vietnã, Indonésia (Oeste)",
    8: "UTC+8: China, Filipinas, Malásia, Singapura, Austrália Ocidental",
    9: "UTC+9: Japão, Coreia do Sul, Indonésia Oriental",
    9.5: "UTC+9:30: Austrália Meridional, Território do Norte (Austrália)",
    10: "UTC+10: Queensland (Austrália), Papua Nova Guiné",
    10.5: "UTC+10:30: Ilha Lord Howe (Austrália)",
    11: "UTC+11: Nova Caledônia, Ilhas Salomão",
    12: "UTC+12: Nova Zelândia (maior parte), Fiji, Ilhas Marshall",
    12.75: "UTC+12:45: Ilhas Chatham (Nova Zelândia)",
    13: "UTC+13: Tonga, Samoa, Tokelau",
    14: "UTC+14: Ilhas Line (Kiribati)",
  },
  themeText: "",
  settings: {
    light: "Alternar para Claro",
    dark: "Alternar para Escuro",
  },
  notifications: {
    meetday: {
      title: "📅 Aniversário do Dia que conheceu",
      body: "Você é amigo de ${nickName} desde ${year}!",
    },
    birthday: {
      title: "🎉 Aniversário de ${name}!",
      body: "Deseje um feliz aniversário a ${nickName}!",
    },
    upcomingBirthday: {
      title: "🎉 ¡${name} tem o aniversário em uma semana!",
      body: "Não esqueça de um presente!",
    },
    interaction: {
      title: "💭 Lembrete sobre ${displayName}",
      body: "Não esqueça de entrar em contato com ${displayName}!",
    },
  },
  emptyMessage: "Ainda não há amigos adicionados. Adicione alguns amigos!",
  sortHeader: "Opções de Ordenação",
  "interaction-btn-disabled": "Adiciona contato",
};
