export default {
  title: "",
  header: "",
  defaultFriendDescription: "",
  addFriendHeader: "",
  addFriendBtn: "",
  friendDetailHeader: "",
  settingsHeader: "",
  createProfile: "",
  changeLayout: "",
  changeLanguage: "",
  exportImportFriends: "",
  importContacts: "",
  changeDescription: "",
  reportBug: "",
  resetApp: "",
  redeemCode: "",
  searchInput: "",
  friendNameInput: "",
  friendNickInput: "",
  friendTimezoneInput: "",
  friendBirthdayInput: "",
  friendTagsInput: "",
  friendNameLabel: "",
  friendNickLabel: "",
  friendTimezoneLabel: "",
  friendNumberLabel: "",
  friendBirthdayLabel: "",
  friendMeetdayLabel: "",
  friendImageLabel: "",
  nowBtn: "",
  friendTagsLabel: "",
  totalContacts: "",
  permissionDenied: "",
  unknown: "",
  noTags: "",
  friendNotFound: "",
  friendNotFoundParams: "",
  birthday: "",
  meetday: "",
  totalContactsSelected: "",
  alertErrorReset: "",
  modal: {
    default: {
      title: "",
      message: "",
      confirmText: "",
      cancelText: "",
    },
    revert: {
      title: "",
    },
    delete: {
      title: "",
    },
    tags: {
      title: "",
      description: "",
      message: "",
      confirmText: "",
      cancelText: "",
    },
    importContacts: {
      title: "",
      message: "",
      confirmText: "",
      cancelText: "",
    },
    deleteFriend: {
      title: "",
    },
    list: {
      title: "",
      message: "",
      confirmText: "",
      cancelText: "",
    },
    langs: {
      title: "",
      message: "",
      confirmText: "",
      cancelText: "",
    },
    langConfirm: {
      title: "",
      message: "",
      confirmText: "",
    },
    order: {
      title: "",
      message: "",
      confirmText: "",
      cancelText: "",
      options: ["", "", "", "", "", "", ""],
    },
    orderConfirm: {
      title: "",
      message: "",
      confirmText: "",
    },
    defaultDesc: {
      title: "",
      message: "",
      confirmText: "",
      cancelText: "",
    },
    addNotification: {
      title: "",
      message: "",
      confirmText: "",
      labels: {
        title: "",
        titlePlaceholder: "",
        body: "",
        bodyPlaceholder: "",
        date: "",
        repeats: "",
      },
      priorities: {
        low: "",
        medium: "",
        high: "",
      },
      repeats: {
        no: "",
        year: "",
        month: "",
        week: "",
        day: "",
      },
    },
    editFriend: {
      title: "",
      message: "",
      labels: {
        name: "",
        nick: "",
        contact: "",
        timezone: "",
        birthday: "",
        meetday: "",
      },
      placeholders: {
        contact: "",
      },
    },
  },
  "notification-btn": "",
  dateNotInformed: "",
  noNewContactsFound: "",
  contactsError: "",
  timezoneOptions: {
    "-12": "",
    "-11": "",
    "-10": "",
    "-9": "",
    "-8": "",
    "-7": "",
    "-6": "",
    "-5": "",
    "-4": "",
    "-3.5": "",
    "-3": "",
    "-2": "",
    "-1": "",
    0: "",
    1: "",
    2: "",
    3: "",
    3.5: "",
    4: "",
    4.5: "",
    5: "",
    5.5: "",
    5.75: "",
    6: "",
    6.5: "",
    7: "",
    8: "",
    9: "",
    9.5: "",
    10: "",
    10.5: "",
    11: "",
    12: "",
    12.75: "",
    13: "",
    14: "",
  },
  themeText: "",
  settings: {
    light: "",
    dark: "",
  },
  notifications: {
    meetday: {
      title: "",
      body: "",
    },
    birthday: {
      title: "",
      body: "",
    },
    interaction: {
      title: "",
      body: "",
    },
  },
  sortHeader: "",
  emptyMessage: "",
};
